tests: Add option parsing tests

diff --git a/tests/Makefile b/tests/Makefile
--- a/tests/Makefile
+++ b/tests/Makefile
@@ -1,4 +1,10 @@
 PROGRAM_EXEC=../src/$(PROGRAM_NAME)
 
 all:
-	sh ./001-missing_arguments.sh $(PROGRAM_EXEC)
+	for t in [0-9]*.sh ; do \
+	  echo $$t; \
+	  sh ./$$t ../src/diff-dd; \
+	  # Testing of the return value must return true on the test failure. \
+	  # If the return value is zero, it means a successful test. \
+	  [ $$? -ne 0 ] && exit 1 || true; \
+	done
